// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: WhisperTextProtocol.proto
// Protobuf C++ Version: 6.33.4

#ifndef WhisperTextProtocol_2eproto_2epb_2eh
#define WhisperTextProtocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_WhisperTextProtocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_WhisperTextProtocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_WhisperTextProtocol_2eproto;
}  // extern "C"
namespace textsecure {
class KeyExchangeMessage;
struct KeyExchangeMessageDefaultTypeInternal;
extern KeyExchangeMessageDefaultTypeInternal _KeyExchangeMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull KeyExchangeMessage_class_data_;
class PreKeyWhisperMessage;
struct PreKeyWhisperMessageDefaultTypeInternal;
extern PreKeyWhisperMessageDefaultTypeInternal _PreKeyWhisperMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PreKeyWhisperMessage_class_data_;
class WhisperMessage;
struct WhisperMessageDefaultTypeInternal;
extern WhisperMessageDefaultTypeInternal _WhisperMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WhisperMessage_class_data_;
}  // namespace textsecure
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace textsecure {

// ===================================================================


// -------------------------------------------------------------------

class WhisperMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:textsecure.WhisperMessage) */ {
 public:
  inline WhisperMessage() : WhisperMessage(nullptr) {}
  ~WhisperMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WhisperMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WhisperMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WhisperMessage(::google::protobuf::internal::ConstantInitialized);

  inline WhisperMessage(const WhisperMessage& from) : WhisperMessage(nullptr, from) {}
  inline WhisperMessage(WhisperMessage&& from) noexcept
      : WhisperMessage(nullptr, ::std::move(from)) {}
  inline WhisperMessage& operator=(const WhisperMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline WhisperMessage& operator=(WhisperMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WhisperMessage& default_instance() {
    return *reinterpret_cast<const WhisperMessage*>(
        &_WhisperMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WhisperMessage& a, WhisperMessage& b) { a.Swap(&b); }
  inline void Swap(WhisperMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WhisperMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WhisperMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WhisperMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WhisperMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WhisperMessage& from) { WhisperMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WhisperMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "textsecure.WhisperMessage"; }

  explicit WhisperMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WhisperMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WhisperMessage& from);
  WhisperMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WhisperMessage&& from) noexcept
      : WhisperMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEphemeralKeyFieldNumber = 1,
    kCiphertextFieldNumber = 4,
    kCounterFieldNumber = 2,
    kPreviousCounterFieldNumber = 3,
  };
  // optional bytes ephemeralKey = 1;
  bool has_ephemeralkey() const;
  void clear_ephemeralkey() ;
  const ::std::string& ephemeralkey() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ephemeralkey(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ephemeralkey();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ephemeralkey();
  void set_allocated_ephemeralkey(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ephemeralkey() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ephemeralkey(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ephemeralkey();

  public:
  // optional bytes ciphertext = 4;
  bool has_ciphertext() const;
  void clear_ciphertext() ;
  const ::std::string& ciphertext() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ciphertext(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ciphertext();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ciphertext();
  void set_allocated_ciphertext(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ciphertext() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ciphertext(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ciphertext();

  public:
  // optional uint32 counter = 2;
  bool has_counter() const;
  void clear_counter() ;
  ::uint32_t counter() const;
  void set_counter(::uint32_t value);

  private:
  ::uint32_t _internal_counter() const;
  void _internal_set_counter(::uint32_t value);

  public:
  // optional uint32 previousCounter = 3;
  bool has_previouscounter() const;
  void clear_previouscounter() ;
  ::uint32_t previouscounter() const;
  void set_previouscounter(::uint32_t value);

  private:
  ::uint32_t _internal_previouscounter() const;
  void _internal_set_previouscounter(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:textsecure.WhisperMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WhisperMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ephemeralkey_;
    ::google::protobuf::internal::ArenaStringPtr ciphertext_;
    ::uint32_t counter_;
    ::uint32_t previouscounter_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WhisperTextProtocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WhisperMessage_class_data_;
// -------------------------------------------------------------------

class PreKeyWhisperMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:textsecure.PreKeyWhisperMessage) */ {
 public:
  inline PreKeyWhisperMessage() : PreKeyWhisperMessage(nullptr) {}
  ~PreKeyWhisperMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PreKeyWhisperMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PreKeyWhisperMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PreKeyWhisperMessage(::google::protobuf::internal::ConstantInitialized);

  inline PreKeyWhisperMessage(const PreKeyWhisperMessage& from) : PreKeyWhisperMessage(nullptr, from) {}
  inline PreKeyWhisperMessage(PreKeyWhisperMessage&& from) noexcept
      : PreKeyWhisperMessage(nullptr, ::std::move(from)) {}
  inline PreKeyWhisperMessage& operator=(const PreKeyWhisperMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PreKeyWhisperMessage& operator=(PreKeyWhisperMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PreKeyWhisperMessage& default_instance() {
    return *reinterpret_cast<const PreKeyWhisperMessage*>(
        &_PreKeyWhisperMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PreKeyWhisperMessage& a, PreKeyWhisperMessage& b) { a.Swap(&b); }
  inline void Swap(PreKeyWhisperMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PreKeyWhisperMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PreKeyWhisperMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PreKeyWhisperMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PreKeyWhisperMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PreKeyWhisperMessage& from) { PreKeyWhisperMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PreKeyWhisperMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "textsecure.PreKeyWhisperMessage"; }

  explicit PreKeyWhisperMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PreKeyWhisperMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PreKeyWhisperMessage& from);
  PreKeyWhisperMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PreKeyWhisperMessage&& from) noexcept
      : PreKeyWhisperMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBaseKeyFieldNumber = 2,
    kIdentityKeyFieldNumber = 3,
    kMessageFieldNumber = 4,
    kPreKeyIdFieldNumber = 1,
    kRegistrationIdFieldNumber = 5,
    kSignedPreKeyIdFieldNumber = 6,
  };
  // optional bytes baseKey = 2;
  bool has_basekey() const;
  void clear_basekey() ;
  const ::std::string& basekey() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_basekey(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_basekey();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_basekey();
  void set_allocated_basekey(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_basekey() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_basekey(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_basekey();

  public:
  // optional bytes identityKey = 3;
  bool has_identitykey() const;
  void clear_identitykey() ;
  const ::std::string& identitykey() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_identitykey(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_identitykey();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_identitykey();
  void set_allocated_identitykey(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_identitykey() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_identitykey(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_identitykey();

  public:
  // optional bytes message = 4;
  bool has_message() const;
  void clear_message() ;
  const ::std::string& message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  // optional uint32 preKeyId = 1;
  bool has_prekeyid() const;
  void clear_prekeyid() ;
  ::uint32_t prekeyid() const;
  void set_prekeyid(::uint32_t value);

  private:
  ::uint32_t _internal_prekeyid() const;
  void _internal_set_prekeyid(::uint32_t value);

  public:
  // optional uint32 registrationId = 5;
  bool has_registrationid() const;
  void clear_registrationid() ;
  ::uint32_t registrationid() const;
  void set_registrationid(::uint32_t value);

  private:
  ::uint32_t _internal_registrationid() const;
  void _internal_set_registrationid(::uint32_t value);

  public:
  // optional uint32 signedPreKeyId = 6;
  bool has_signedprekeyid() const;
  void clear_signedprekeyid() ;
  ::uint32_t signedprekeyid() const;
  void set_signedprekeyid(::uint32_t value);

  private:
  ::uint32_t _internal_signedprekeyid() const;
  void _internal_set_signedprekeyid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:textsecure.PreKeyWhisperMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PreKeyWhisperMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr basekey_;
    ::google::protobuf::internal::ArenaStringPtr identitykey_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::uint32_t prekeyid_;
    ::uint32_t registrationid_;
    ::uint32_t signedprekeyid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WhisperTextProtocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PreKeyWhisperMessage_class_data_;
// -------------------------------------------------------------------

class KeyExchangeMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:textsecure.KeyExchangeMessage) */ {
 public:
  inline KeyExchangeMessage() : KeyExchangeMessage(nullptr) {}
  ~KeyExchangeMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(KeyExchangeMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(KeyExchangeMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR KeyExchangeMessage(::google::protobuf::internal::ConstantInitialized);

  inline KeyExchangeMessage(const KeyExchangeMessage& from) : KeyExchangeMessage(nullptr, from) {}
  inline KeyExchangeMessage(KeyExchangeMessage&& from) noexcept
      : KeyExchangeMessage(nullptr, ::std::move(from)) {}
  inline KeyExchangeMessage& operator=(const KeyExchangeMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyExchangeMessage& operator=(KeyExchangeMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KeyExchangeMessage& default_instance() {
    return *reinterpret_cast<const KeyExchangeMessage*>(
        &_KeyExchangeMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(KeyExchangeMessage& a, KeyExchangeMessage& b) { a.Swap(&b); }
  inline void Swap(KeyExchangeMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyExchangeMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KeyExchangeMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<KeyExchangeMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const KeyExchangeMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const KeyExchangeMessage& from) { KeyExchangeMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(KeyExchangeMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "textsecure.KeyExchangeMessage"; }

  explicit KeyExchangeMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  KeyExchangeMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const KeyExchangeMessage& from);
  KeyExchangeMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, KeyExchangeMessage&& from) noexcept
      : KeyExchangeMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBaseKeyFieldNumber = 2,
    kEphemeralKeyFieldNumber = 3,
    kIdentityKeyFieldNumber = 4,
    kBaseKeySignatureFieldNumber = 5,
    kIdFieldNumber = 1,
  };
  // optional bytes baseKey = 2;
  bool has_basekey() const;
  void clear_basekey() ;
  const ::std::string& basekey() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_basekey(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_basekey();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_basekey();
  void set_allocated_basekey(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_basekey() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_basekey(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_basekey();

  public:
  // optional bytes ephemeralKey = 3;
  bool has_ephemeralkey() const;
  void clear_ephemeralkey() ;
  const ::std::string& ephemeralkey() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ephemeralkey(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ephemeralkey();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ephemeralkey();
  void set_allocated_ephemeralkey(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ephemeralkey() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ephemeralkey(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ephemeralkey();

  public:
  // optional bytes identityKey = 4;
  bool has_identitykey() const;
  void clear_identitykey() ;
  const ::std::string& identitykey() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_identitykey(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_identitykey();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_identitykey();
  void set_allocated_identitykey(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_identitykey() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_identitykey(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_identitykey();

  public:
  // optional bytes baseKeySignature = 5;
  bool has_basekeysignature() const;
  void clear_basekeysignature() ;
  const ::std::string& basekeysignature() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_basekeysignature(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_basekeysignature();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_basekeysignature();
  void set_allocated_basekeysignature(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_basekeysignature() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_basekeysignature(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_basekeysignature();

  public:
  // optional uint32 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:textsecure.KeyExchangeMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const KeyExchangeMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr basekey_;
    ::google::protobuf::internal::ArenaStringPtr ephemeralkey_;
    ::google::protobuf::internal::ArenaStringPtr identitykey_;
    ::google::protobuf::internal::ArenaStringPtr basekeysignature_;
    ::uint32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WhisperTextProtocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull KeyExchangeMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WhisperMessage

// optional bytes ephemeralKey = 1;
inline bool WhisperMessage::has_ephemeralkey() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void WhisperMessage::clear_ephemeralkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ephemeralkey_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& WhisperMessage::ephemeralkey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.WhisperMessage.ephemeralKey)
  return _internal_ephemeralkey();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void WhisperMessage::set_ephemeralkey(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.ephemeralkey_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.WhisperMessage.ephemeralKey)
}
inline ::std::string* PROTOBUF_NONNULL WhisperMessage::mutable_ephemeralkey()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_ephemeralkey();
  // @@protoc_insertion_point(field_mutable:textsecure.WhisperMessage.ephemeralKey)
  return _s;
}
inline const ::std::string& WhisperMessage::_internal_ephemeralkey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ephemeralkey_.Get();
}
inline void WhisperMessage::_internal_set_ephemeralkey(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ephemeralkey_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL WhisperMessage::_internal_mutable_ephemeralkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ephemeralkey_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE WhisperMessage::release_ephemeralkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.WhisperMessage.ephemeralKey)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.ephemeralkey_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ephemeralkey_.Set("", GetArena());
  }
  return released;
}
inline void WhisperMessage::set_allocated_ephemeralkey(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.ephemeralkey_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ephemeralkey_.IsDefault()) {
    _impl_.ephemeralkey_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.WhisperMessage.ephemeralKey)
}

// optional uint32 counter = 2;
inline bool WhisperMessage::has_counter() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void WhisperMessage::clear_counter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.counter_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t WhisperMessage::counter() const {
  // @@protoc_insertion_point(field_get:textsecure.WhisperMessage.counter)
  return _internal_counter();
}
inline void WhisperMessage::set_counter(::uint32_t value) {
  _internal_set_counter(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:textsecure.WhisperMessage.counter)
}
inline ::uint32_t WhisperMessage::_internal_counter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.counter_;
}
inline void WhisperMessage::_internal_set_counter(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.counter_ = value;
}

// optional uint32 previousCounter = 3;
inline bool WhisperMessage::has_previouscounter() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void WhisperMessage::clear_previouscounter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.previouscounter_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t WhisperMessage::previouscounter() const {
  // @@protoc_insertion_point(field_get:textsecure.WhisperMessage.previousCounter)
  return _internal_previouscounter();
}
inline void WhisperMessage::set_previouscounter(::uint32_t value) {
  _internal_set_previouscounter(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:textsecure.WhisperMessage.previousCounter)
}
inline ::uint32_t WhisperMessage::_internal_previouscounter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.previouscounter_;
}
inline void WhisperMessage::_internal_set_previouscounter(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.previouscounter_ = value;
}

// optional bytes ciphertext = 4;
inline bool WhisperMessage::has_ciphertext() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void WhisperMessage::clear_ciphertext() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ciphertext_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& WhisperMessage::ciphertext() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.WhisperMessage.ciphertext)
  return _internal_ciphertext();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void WhisperMessage::set_ciphertext(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.ciphertext_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.WhisperMessage.ciphertext)
}
inline ::std::string* PROTOBUF_NONNULL WhisperMessage::mutable_ciphertext()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_ciphertext();
  // @@protoc_insertion_point(field_mutable:textsecure.WhisperMessage.ciphertext)
  return _s;
}
inline const ::std::string& WhisperMessage::_internal_ciphertext() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ciphertext_.Get();
}
inline void WhisperMessage::_internal_set_ciphertext(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ciphertext_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL WhisperMessage::_internal_mutable_ciphertext() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ciphertext_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE WhisperMessage::release_ciphertext() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.WhisperMessage.ciphertext)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.ciphertext_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ciphertext_.Set("", GetArena());
  }
  return released;
}
inline void WhisperMessage::set_allocated_ciphertext(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.ciphertext_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ciphertext_.IsDefault()) {
    _impl_.ciphertext_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.WhisperMessage.ciphertext)
}

// -------------------------------------------------------------------

// PreKeyWhisperMessage

// optional uint32 registrationId = 5;
inline bool PreKeyWhisperMessage::has_registrationid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void PreKeyWhisperMessage::clear_registrationid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.registrationid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t PreKeyWhisperMessage::registrationid() const {
  // @@protoc_insertion_point(field_get:textsecure.PreKeyWhisperMessage.registrationId)
  return _internal_registrationid();
}
inline void PreKeyWhisperMessage::set_registrationid(::uint32_t value) {
  _internal_set_registrationid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:textsecure.PreKeyWhisperMessage.registrationId)
}
inline ::uint32_t PreKeyWhisperMessage::_internal_registrationid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.registrationid_;
}
inline void PreKeyWhisperMessage::_internal_set_registrationid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.registrationid_ = value;
}

// optional uint32 preKeyId = 1;
inline bool PreKeyWhisperMessage::has_prekeyid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void PreKeyWhisperMessage::clear_prekeyid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prekeyid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t PreKeyWhisperMessage::prekeyid() const {
  // @@protoc_insertion_point(field_get:textsecure.PreKeyWhisperMessage.preKeyId)
  return _internal_prekeyid();
}
inline void PreKeyWhisperMessage::set_prekeyid(::uint32_t value) {
  _internal_set_prekeyid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:textsecure.PreKeyWhisperMessage.preKeyId)
}
inline ::uint32_t PreKeyWhisperMessage::_internal_prekeyid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prekeyid_;
}
inline void PreKeyWhisperMessage::_internal_set_prekeyid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prekeyid_ = value;
}

// optional uint32 signedPreKeyId = 6;
inline bool PreKeyWhisperMessage::has_signedprekeyid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void PreKeyWhisperMessage::clear_signedprekeyid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signedprekeyid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t PreKeyWhisperMessage::signedprekeyid() const {
  // @@protoc_insertion_point(field_get:textsecure.PreKeyWhisperMessage.signedPreKeyId)
  return _internal_signedprekeyid();
}
inline void PreKeyWhisperMessage::set_signedprekeyid(::uint32_t value) {
  _internal_set_signedprekeyid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:textsecure.PreKeyWhisperMessage.signedPreKeyId)
}
inline ::uint32_t PreKeyWhisperMessage::_internal_signedprekeyid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signedprekeyid_;
}
inline void PreKeyWhisperMessage::_internal_set_signedprekeyid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signedprekeyid_ = value;
}

// optional bytes baseKey = 2;
inline bool PreKeyWhisperMessage::has_basekey() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PreKeyWhisperMessage::clear_basekey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.basekey_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PreKeyWhisperMessage::basekey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.PreKeyWhisperMessage.baseKey)
  return _internal_basekey();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PreKeyWhisperMessage::set_basekey(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.basekey_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.PreKeyWhisperMessage.baseKey)
}
inline ::std::string* PROTOBUF_NONNULL PreKeyWhisperMessage::mutable_basekey()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_basekey();
  // @@protoc_insertion_point(field_mutable:textsecure.PreKeyWhisperMessage.baseKey)
  return _s;
}
inline const ::std::string& PreKeyWhisperMessage::_internal_basekey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.basekey_.Get();
}
inline void PreKeyWhisperMessage::_internal_set_basekey(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.basekey_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PreKeyWhisperMessage::_internal_mutable_basekey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.basekey_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PreKeyWhisperMessage::release_basekey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.PreKeyWhisperMessage.baseKey)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.basekey_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.basekey_.Set("", GetArena());
  }
  return released;
}
inline void PreKeyWhisperMessage::set_allocated_basekey(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.basekey_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.basekey_.IsDefault()) {
    _impl_.basekey_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.PreKeyWhisperMessage.baseKey)
}

// optional bytes identityKey = 3;
inline bool PreKeyWhisperMessage::has_identitykey() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void PreKeyWhisperMessage::clear_identitykey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identitykey_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PreKeyWhisperMessage::identitykey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.PreKeyWhisperMessage.identityKey)
  return _internal_identitykey();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PreKeyWhisperMessage::set_identitykey(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.identitykey_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.PreKeyWhisperMessage.identityKey)
}
inline ::std::string* PROTOBUF_NONNULL PreKeyWhisperMessage::mutable_identitykey()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_identitykey();
  // @@protoc_insertion_point(field_mutable:textsecure.PreKeyWhisperMessage.identityKey)
  return _s;
}
inline const ::std::string& PreKeyWhisperMessage::_internal_identitykey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identitykey_.Get();
}
inline void PreKeyWhisperMessage::_internal_set_identitykey(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identitykey_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PreKeyWhisperMessage::_internal_mutable_identitykey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.identitykey_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PreKeyWhisperMessage::release_identitykey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.PreKeyWhisperMessage.identityKey)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.identitykey_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.identitykey_.Set("", GetArena());
  }
  return released;
}
inline void PreKeyWhisperMessage::set_allocated_identitykey(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.identitykey_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identitykey_.IsDefault()) {
    _impl_.identitykey_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.PreKeyWhisperMessage.identityKey)
}

// optional bytes message = 4;
inline bool PreKeyWhisperMessage::has_message() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void PreKeyWhisperMessage::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& PreKeyWhisperMessage::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.PreKeyWhisperMessage.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PreKeyWhisperMessage::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.message_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.PreKeyWhisperMessage.message)
}
inline ::std::string* PROTOBUF_NONNULL PreKeyWhisperMessage::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:textsecure.PreKeyWhisperMessage.message)
  return _s;
}
inline const ::std::string& PreKeyWhisperMessage::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void PreKeyWhisperMessage::_internal_set_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PreKeyWhisperMessage::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PreKeyWhisperMessage::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.PreKeyWhisperMessage.message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void PreKeyWhisperMessage::set_allocated_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.PreKeyWhisperMessage.message)
}

// -------------------------------------------------------------------

// KeyExchangeMessage

// optional uint32 id = 1;
inline bool KeyExchangeMessage::has_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void KeyExchangeMessage::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t KeyExchangeMessage::id() const {
  // @@protoc_insertion_point(field_get:textsecure.KeyExchangeMessage.id)
  return _internal_id();
}
inline void KeyExchangeMessage::set_id(::uint32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:textsecure.KeyExchangeMessage.id)
}
inline ::uint32_t KeyExchangeMessage::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void KeyExchangeMessage::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// optional bytes baseKey = 2;
inline bool KeyExchangeMessage::has_basekey() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void KeyExchangeMessage::clear_basekey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.basekey_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& KeyExchangeMessage::basekey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.KeyExchangeMessage.baseKey)
  return _internal_basekey();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void KeyExchangeMessage::set_basekey(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.basekey_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.KeyExchangeMessage.baseKey)
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::mutable_basekey()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_basekey();
  // @@protoc_insertion_point(field_mutable:textsecure.KeyExchangeMessage.baseKey)
  return _s;
}
inline const ::std::string& KeyExchangeMessage::_internal_basekey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.basekey_.Get();
}
inline void KeyExchangeMessage::_internal_set_basekey(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.basekey_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::_internal_mutable_basekey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.basekey_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE KeyExchangeMessage::release_basekey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.KeyExchangeMessage.baseKey)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.basekey_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.basekey_.Set("", GetArena());
  }
  return released;
}
inline void KeyExchangeMessage::set_allocated_basekey(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.basekey_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.basekey_.IsDefault()) {
    _impl_.basekey_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.KeyExchangeMessage.baseKey)
}

// optional bytes ephemeralKey = 3;
inline bool KeyExchangeMessage::has_ephemeralkey() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void KeyExchangeMessage::clear_ephemeralkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ephemeralkey_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& KeyExchangeMessage::ephemeralkey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.KeyExchangeMessage.ephemeralKey)
  return _internal_ephemeralkey();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void KeyExchangeMessage::set_ephemeralkey(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.ephemeralkey_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.KeyExchangeMessage.ephemeralKey)
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::mutable_ephemeralkey()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_ephemeralkey();
  // @@protoc_insertion_point(field_mutable:textsecure.KeyExchangeMessage.ephemeralKey)
  return _s;
}
inline const ::std::string& KeyExchangeMessage::_internal_ephemeralkey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ephemeralkey_.Get();
}
inline void KeyExchangeMessage::_internal_set_ephemeralkey(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ephemeralkey_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::_internal_mutable_ephemeralkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ephemeralkey_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE KeyExchangeMessage::release_ephemeralkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.KeyExchangeMessage.ephemeralKey)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.ephemeralkey_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ephemeralkey_.Set("", GetArena());
  }
  return released;
}
inline void KeyExchangeMessage::set_allocated_ephemeralkey(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.ephemeralkey_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ephemeralkey_.IsDefault()) {
    _impl_.ephemeralkey_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.KeyExchangeMessage.ephemeralKey)
}

// optional bytes identityKey = 4;
inline bool KeyExchangeMessage::has_identitykey() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void KeyExchangeMessage::clear_identitykey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identitykey_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& KeyExchangeMessage::identitykey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.KeyExchangeMessage.identityKey)
  return _internal_identitykey();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void KeyExchangeMessage::set_identitykey(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.identitykey_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.KeyExchangeMessage.identityKey)
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::mutable_identitykey()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_identitykey();
  // @@protoc_insertion_point(field_mutable:textsecure.KeyExchangeMessage.identityKey)
  return _s;
}
inline const ::std::string& KeyExchangeMessage::_internal_identitykey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identitykey_.Get();
}
inline void KeyExchangeMessage::_internal_set_identitykey(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identitykey_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::_internal_mutable_identitykey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.identitykey_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE KeyExchangeMessage::release_identitykey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.KeyExchangeMessage.identityKey)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.identitykey_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.identitykey_.Set("", GetArena());
  }
  return released;
}
inline void KeyExchangeMessage::set_allocated_identitykey(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.identitykey_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identitykey_.IsDefault()) {
    _impl_.identitykey_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.KeyExchangeMessage.identityKey)
}

// optional bytes baseKeySignature = 5;
inline bool KeyExchangeMessage::has_basekeysignature() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void KeyExchangeMessage::clear_basekeysignature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.basekeysignature_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& KeyExchangeMessage::basekeysignature() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textsecure.KeyExchangeMessage.baseKeySignature)
  return _internal_basekeysignature();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void KeyExchangeMessage::set_basekeysignature(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.basekeysignature_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textsecure.KeyExchangeMessage.baseKeySignature)
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::mutable_basekeysignature()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_basekeysignature();
  // @@protoc_insertion_point(field_mutable:textsecure.KeyExchangeMessage.baseKeySignature)
  return _s;
}
inline const ::std::string& KeyExchangeMessage::_internal_basekeysignature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.basekeysignature_.Get();
}
inline void KeyExchangeMessage::_internal_set_basekeysignature(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.basekeysignature_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL KeyExchangeMessage::_internal_mutable_basekeysignature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.basekeysignature_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE KeyExchangeMessage::release_basekeysignature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textsecure.KeyExchangeMessage.baseKeySignature)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.basekeysignature_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.basekeysignature_.Set("", GetArena());
  }
  return released;
}
inline void KeyExchangeMessage::set_allocated_basekeysignature(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.basekeysignature_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.basekeysignature_.IsDefault()) {
    _impl_.basekeysignature_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textsecure.KeyExchangeMessage.baseKeySignature)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace textsecure


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // WhisperTextProtocol_2eproto_2epb_2eh
