// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: WhisperTextProtocol.proto
// Protobuf C++ Version: 6.33.4

#include "WhisperTextProtocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace textsecure {

inline constexpr WhisperMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ephemeralkey_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ciphertext_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        counter_{0u},
        previouscounter_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR WhisperMessage::WhisperMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WhisperMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WhisperMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WhisperMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WhisperMessageDefaultTypeInternal() {}
  union {
    WhisperMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WhisperMessageDefaultTypeInternal _WhisperMessage_default_instance_;

inline constexpr PreKeyWhisperMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        basekey_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        identitykey_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        prekeyid_{0u},
        registrationid_{0u},
        signedprekeyid_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR PreKeyWhisperMessage::PreKeyWhisperMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PreKeyWhisperMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PreKeyWhisperMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PreKeyWhisperMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PreKeyWhisperMessageDefaultTypeInternal() {}
  union {
    PreKeyWhisperMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PreKeyWhisperMessageDefaultTypeInternal _PreKeyWhisperMessage_default_instance_;

inline constexpr KeyExchangeMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        basekey_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ephemeralkey_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        identitykey_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        basekeysignature_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR KeyExchangeMessage::KeyExchangeMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(KeyExchangeMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct KeyExchangeMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeyExchangeMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyExchangeMessageDefaultTypeInternal() {}
  union {
    KeyExchangeMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyExchangeMessageDefaultTypeInternal _KeyExchangeMessage_default_instance_;
}  // namespace textsecure
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_WhisperTextProtocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_WhisperTextProtocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_WhisperTextProtocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::textsecure::WhisperMessage, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::textsecure::WhisperMessage, _impl_.ephemeralkey_),
        PROTOBUF_FIELD_OFFSET(::textsecure::WhisperMessage, _impl_.counter_),
        PROTOBUF_FIELD_OFFSET(::textsecure::WhisperMessage, _impl_.previouscounter_),
        PROTOBUF_FIELD_OFFSET(::textsecure::WhisperMessage, _impl_.ciphertext_),
        0,
        2,
        3,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::textsecure::PreKeyWhisperMessage, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::textsecure::PreKeyWhisperMessage, _impl_.registrationid_),
        PROTOBUF_FIELD_OFFSET(::textsecure::PreKeyWhisperMessage, _impl_.prekeyid_),
        PROTOBUF_FIELD_OFFSET(::textsecure::PreKeyWhisperMessage, _impl_.signedprekeyid_),
        PROTOBUF_FIELD_OFFSET(::textsecure::PreKeyWhisperMessage, _impl_.basekey_),
        PROTOBUF_FIELD_OFFSET(::textsecure::PreKeyWhisperMessage, _impl_.identitykey_),
        PROTOBUF_FIELD_OFFSET(::textsecure::PreKeyWhisperMessage, _impl_.message_),
        4,
        3,
        5,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::textsecure::KeyExchangeMessage, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::textsecure::KeyExchangeMessage, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::textsecure::KeyExchangeMessage, _impl_.basekey_),
        PROTOBUF_FIELD_OFFSET(::textsecure::KeyExchangeMessage, _impl_.ephemeralkey_),
        PROTOBUF_FIELD_OFFSET(::textsecure::KeyExchangeMessage, _impl_.identitykey_),
        PROTOBUF_FIELD_OFFSET(::textsecure::KeyExchangeMessage, _impl_.basekeysignature_),
        4,
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::textsecure::WhisperMessage)},
        {11, sizeof(::textsecure::PreKeyWhisperMessage)},
        {26, sizeof(::textsecure::KeyExchangeMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::textsecure::_WhisperMessage_default_instance_._instance,
    &::textsecure::_PreKeyWhisperMessage_default_instance_._instance,
    &::textsecure::_KeyExchangeMessage_default_instance_._instance,
};
const char descriptor_table_protodef_WhisperTextProtocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031WhisperTextProtocol.proto\022\ntextsecure\""
    "d\n\016WhisperMessage\022\024\n\014ephemeralKey\030\001 \001(\014\022"
    "\017\n\007counter\030\002 \001(\r\022\027\n\017previousCounter\030\003 \001("
    "\r\022\022\n\nciphertext\030\004 \001(\014\"\217\001\n\024PreKeyWhisperM"
    "essage\022\026\n\016registrationId\030\005 \001(\r\022\020\n\010preKey"
    "Id\030\001 \001(\r\022\026\n\016signedPreKeyId\030\006 \001(\r\022\017\n\007base"
    "Key\030\002 \001(\014\022\023\n\013identityKey\030\003 \001(\014\022\017\n\007messag"
    "e\030\004 \001(\014\"v\n\022KeyExchangeMessage\022\n\n\002id\030\001 \001("
    "\r\022\017\n\007baseKey\030\002 \001(\014\022\024\n\014ephemeralKey\030\003 \001(\014"
    "\022\023\n\013identityKey\030\004 \001(\014\022\030\n\020baseKeySignatur"
    "e\030\005 \001(\014B6\n%org.whispersystems.libsignal."
    "protocolB\rWhisperProtos"
};
static ::absl::once_flag descriptor_table_WhisperTextProtocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_WhisperTextProtocol_2eproto = {
    false,
    false,
    463,
    descriptor_table_protodef_WhisperTextProtocol_2eproto,
    "WhisperTextProtocol.proto",
    &descriptor_table_WhisperTextProtocol_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_WhisperTextProtocol_2eproto::offsets,
    file_level_enum_descriptors_WhisperTextProtocol_2eproto,
    file_level_service_descriptors_WhisperTextProtocol_2eproto,
};
namespace textsecure {
// ===================================================================

class WhisperMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WhisperMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_._has_bits_);
};

WhisperMessage::WhisperMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WhisperMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:textsecure.WhisperMessage)
}
PROTOBUF_NDEBUG_INLINE WhisperMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::textsecure::WhisperMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ephemeralkey_(arena, from.ephemeralkey_),
        ciphertext_(arena, from.ciphertext_) {}

WhisperMessage::WhisperMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WhisperMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WhisperMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WhisperMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, counter_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, counter_),
           offsetof(Impl_, previouscounter_) -
               offsetof(Impl_, counter_) +
               sizeof(Impl_::previouscounter_));

  // @@protoc_insertion_point(copy_constructor:textsecure.WhisperMessage)
}
PROTOBUF_NDEBUG_INLINE WhisperMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ephemeralkey_(arena),
        ciphertext_(arena) {}

inline void WhisperMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, counter_),
           0,
           offsetof(Impl_, previouscounter_) -
               offsetof(Impl_, counter_) +
               sizeof(Impl_::previouscounter_));
}
WhisperMessage::~WhisperMessage() {
  // @@protoc_insertion_point(destructor:textsecure.WhisperMessage)
  SharedDtor(*this);
}
inline void WhisperMessage::SharedDtor(MessageLite& self) {
  WhisperMessage& this_ = static_cast<WhisperMessage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ephemeralkey_.Destroy();
  this_._impl_.ciphertext_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WhisperMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WhisperMessage(arena);
}
constexpr auto WhisperMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WhisperMessage),
                                            alignof(WhisperMessage));
}
constexpr auto WhisperMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WhisperMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WhisperMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WhisperMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WhisperMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WhisperMessage>(), &WhisperMessage::ByteSizeLong,
              &WhisperMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_._cached_size_),
          false,
      },
      &WhisperMessage::kDescriptorMethods,
      &descriptor_table_WhisperTextProtocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WhisperMessage_class_data_ =
        WhisperMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WhisperMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WhisperMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WhisperMessage_class_data_.tc_table);
  return WhisperMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
WhisperMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WhisperMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::textsecure::WhisperMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bytes ciphertext = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.ciphertext_)}},
    // optional bytes ephemeralKey = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.ephemeralkey_)}},
    // optional uint32 counter = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WhisperMessage, _impl_.counter_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.counter_)}},
    // optional uint32 previousCounter = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WhisperMessage, _impl_.previouscounter_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.previouscounter_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bytes ephemeralKey = 1;
    {PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.ephemeralkey_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 counter = 2;
    {PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.counter_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 previousCounter = 3;
    {PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.previouscounter_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional bytes ciphertext = 4;
    {PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.ciphertext_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void WhisperMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:textsecure.WhisperMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.ephemeralkey_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.ciphertext_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.counter_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.previouscounter_) -
        reinterpret_cast<char*>(&_impl_.counter_)) + sizeof(_impl_.previouscounter_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WhisperMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WhisperMessage& this_ = static_cast<const WhisperMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WhisperMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WhisperMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:textsecure.WhisperMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bytes ephemeralKey = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_ephemeralkey();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // optional uint32 counter = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_counter(), target);
  }

  // optional uint32 previousCounter = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_previouscounter(), target);
  }

  // optional bytes ciphertext = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_ciphertext();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:textsecure.WhisperMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WhisperMessage::ByteSizeLong(const MessageLite& base) {
  const WhisperMessage& this_ = static_cast<const WhisperMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WhisperMessage::ByteSizeLong() const {
  const WhisperMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:textsecure.WhisperMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // optional bytes ephemeralKey = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_ephemeralkey());
    }
    // optional bytes ciphertext = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_ciphertext());
    }
    // optional uint32 counter = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_counter());
    }
    // optional uint32 previousCounter = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_previouscounter());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WhisperMessage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WhisperMessage*>(&to_msg);
  auto& from = static_cast<const WhisperMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:textsecure.WhisperMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_ephemeralkey(from._internal_ephemeralkey());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_ciphertext(from._internal_ciphertext());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.counter_ = from._impl_.counter_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.previouscounter_ = from._impl_.previouscounter_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WhisperMessage::CopyFrom(const WhisperMessage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:textsecure.WhisperMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WhisperMessage::InternalSwap(WhisperMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ephemeralkey_, &other->_impl_.ephemeralkey_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ciphertext_, &other->_impl_.ciphertext_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.previouscounter_)
      + sizeof(WhisperMessage::_impl_.previouscounter_)
      - PROTOBUF_FIELD_OFFSET(WhisperMessage, _impl_.counter_)>(
          reinterpret_cast<char*>(&_impl_.counter_),
          reinterpret_cast<char*>(&other->_impl_.counter_));
}

::google::protobuf::Metadata WhisperMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PreKeyWhisperMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PreKeyWhisperMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_._has_bits_);
};

PreKeyWhisperMessage::PreKeyWhisperMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PreKeyWhisperMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:textsecure.PreKeyWhisperMessage)
}
PROTOBUF_NDEBUG_INLINE PreKeyWhisperMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::textsecure::PreKeyWhisperMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        basekey_(arena, from.basekey_),
        identitykey_(arena, from.identitykey_),
        message_(arena, from.message_) {}

PreKeyWhisperMessage::PreKeyWhisperMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PreKeyWhisperMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PreKeyWhisperMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PreKeyWhisperMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, prekeyid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, prekeyid_),
           offsetof(Impl_, signedprekeyid_) -
               offsetof(Impl_, prekeyid_) +
               sizeof(Impl_::signedprekeyid_));

  // @@protoc_insertion_point(copy_constructor:textsecure.PreKeyWhisperMessage)
}
PROTOBUF_NDEBUG_INLINE PreKeyWhisperMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        basekey_(arena),
        identitykey_(arena),
        message_(arena) {}

inline void PreKeyWhisperMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, prekeyid_),
           0,
           offsetof(Impl_, signedprekeyid_) -
               offsetof(Impl_, prekeyid_) +
               sizeof(Impl_::signedprekeyid_));
}
PreKeyWhisperMessage::~PreKeyWhisperMessage() {
  // @@protoc_insertion_point(destructor:textsecure.PreKeyWhisperMessage)
  SharedDtor(*this);
}
inline void PreKeyWhisperMessage::SharedDtor(MessageLite& self) {
  PreKeyWhisperMessage& this_ = static_cast<PreKeyWhisperMessage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.basekey_.Destroy();
  this_._impl_.identitykey_.Destroy();
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PreKeyWhisperMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PreKeyWhisperMessage(arena);
}
constexpr auto PreKeyWhisperMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PreKeyWhisperMessage),
                                            alignof(PreKeyWhisperMessage));
}
constexpr auto PreKeyWhisperMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PreKeyWhisperMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PreKeyWhisperMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PreKeyWhisperMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PreKeyWhisperMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PreKeyWhisperMessage>(), &PreKeyWhisperMessage::ByteSizeLong,
              &PreKeyWhisperMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_._cached_size_),
          false,
      },
      &PreKeyWhisperMessage::kDescriptorMethods,
      &descriptor_table_WhisperTextProtocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PreKeyWhisperMessage_class_data_ =
        PreKeyWhisperMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PreKeyWhisperMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PreKeyWhisperMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PreKeyWhisperMessage_class_data_.tc_table);
  return PreKeyWhisperMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2>
PreKeyWhisperMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PreKeyWhisperMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::textsecure::PreKeyWhisperMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 preKeyId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PreKeyWhisperMessage, _impl_.prekeyid_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.prekeyid_)}},
    // optional bytes baseKey = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.basekey_)}},
    // optional bytes identityKey = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.identitykey_)}},
    // optional bytes message = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.message_)}},
    // optional uint32 registrationId = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PreKeyWhisperMessage, _impl_.registrationid_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.registrationid_)}},
    // optional uint32 signedPreKeyId = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PreKeyWhisperMessage, _impl_.signedprekeyid_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.signedprekeyid_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 preKeyId = 1;
    {PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.prekeyid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional bytes baseKey = 2;
    {PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.basekey_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bytes identityKey = 3;
    {PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.identitykey_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bytes message = 4;
    {PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.message_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 registrationId = 5;
    {PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.registrationid_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 signedPreKeyId = 6;
    {PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.signedprekeyid_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PreKeyWhisperMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:textsecure.PreKeyWhisperMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.basekey_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.identitykey_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000038U)) {
    ::memset(&_impl_.prekeyid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.signedprekeyid_) -
        reinterpret_cast<char*>(&_impl_.prekeyid_)) + sizeof(_impl_.signedprekeyid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PreKeyWhisperMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PreKeyWhisperMessage& this_ = static_cast<const PreKeyWhisperMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PreKeyWhisperMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PreKeyWhisperMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:textsecure.PreKeyWhisperMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 preKeyId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_prekeyid(), target);
  }

  // optional bytes baseKey = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_basekey();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // optional bytes identityKey = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_identitykey();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  // optional bytes message = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_message();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  // optional uint32 registrationId = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_registrationid(), target);
  }

  // optional uint32 signedPreKeyId = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_signedprekeyid(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:textsecure.PreKeyWhisperMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PreKeyWhisperMessage::ByteSizeLong(const MessageLite& base) {
  const PreKeyWhisperMessage& this_ = static_cast<const PreKeyWhisperMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PreKeyWhisperMessage::ByteSizeLong() const {
  const PreKeyWhisperMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:textsecure.PreKeyWhisperMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // optional bytes baseKey = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_basekey());
    }
    // optional bytes identityKey = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_identitykey());
    }
    // optional bytes message = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_message());
    }
    // optional uint32 preKeyId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_prekeyid());
    }
    // optional uint32 registrationId = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_registrationid());
    }
    // optional uint32 signedPreKeyId = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_signedprekeyid());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PreKeyWhisperMessage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PreKeyWhisperMessage*>(&to_msg);
  auto& from = static_cast<const PreKeyWhisperMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:textsecure.PreKeyWhisperMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_basekey(from._internal_basekey());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_identitykey(from._internal_identitykey());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_message(from._internal_message());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.prekeyid_ = from._impl_.prekeyid_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.registrationid_ = from._impl_.registrationid_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.signedprekeyid_ = from._impl_.signedprekeyid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PreKeyWhisperMessage::CopyFrom(const PreKeyWhisperMessage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:textsecure.PreKeyWhisperMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PreKeyWhisperMessage::InternalSwap(PreKeyWhisperMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.basekey_, &other->_impl_.basekey_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.identitykey_, &other->_impl_.identitykey_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.signedprekeyid_)
      + sizeof(PreKeyWhisperMessage::_impl_.signedprekeyid_)
      - PROTOBUF_FIELD_OFFSET(PreKeyWhisperMessage, _impl_.prekeyid_)>(
          reinterpret_cast<char*>(&_impl_.prekeyid_),
          reinterpret_cast<char*>(&other->_impl_.prekeyid_));
}

::google::protobuf::Metadata PreKeyWhisperMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class KeyExchangeMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<KeyExchangeMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_._has_bits_);
};

KeyExchangeMessage::KeyExchangeMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, KeyExchangeMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:textsecure.KeyExchangeMessage)
}
PROTOBUF_NDEBUG_INLINE KeyExchangeMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::textsecure::KeyExchangeMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        basekey_(arena, from.basekey_),
        ephemeralkey_(arena, from.ephemeralkey_),
        identitykey_(arena, from.identitykey_),
        basekeysignature_(arena, from.basekeysignature_) {}

KeyExchangeMessage::KeyExchangeMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const KeyExchangeMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, KeyExchangeMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  KeyExchangeMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:textsecure.KeyExchangeMessage)
}
PROTOBUF_NDEBUG_INLINE KeyExchangeMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        basekey_(arena),
        ephemeralkey_(arena),
        identitykey_(arena),
        basekeysignature_(arena) {}

inline void KeyExchangeMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
KeyExchangeMessage::~KeyExchangeMessage() {
  // @@protoc_insertion_point(destructor:textsecure.KeyExchangeMessage)
  SharedDtor(*this);
}
inline void KeyExchangeMessage::SharedDtor(MessageLite& self) {
  KeyExchangeMessage& this_ = static_cast<KeyExchangeMessage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.basekey_.Destroy();
  this_._impl_.ephemeralkey_.Destroy();
  this_._impl_.identitykey_.Destroy();
  this_._impl_.basekeysignature_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL KeyExchangeMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) KeyExchangeMessage(arena);
}
constexpr auto KeyExchangeMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(KeyExchangeMessage),
                                            alignof(KeyExchangeMessage));
}
constexpr auto KeyExchangeMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_KeyExchangeMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &KeyExchangeMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<KeyExchangeMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &KeyExchangeMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<KeyExchangeMessage>(), &KeyExchangeMessage::ByteSizeLong,
              &KeyExchangeMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_._cached_size_),
          false,
      },
      &KeyExchangeMessage::kDescriptorMethods,
      &descriptor_table_WhisperTextProtocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull KeyExchangeMessage_class_data_ =
        KeyExchangeMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
KeyExchangeMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&KeyExchangeMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(KeyExchangeMessage_class_data_.tc_table);
  return KeyExchangeMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
KeyExchangeMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    KeyExchangeMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::textsecure::KeyExchangeMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(KeyExchangeMessage, _impl_.id_), 4>(),
     {8, 4, 0,
      PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.id_)}},
    // optional bytes baseKey = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.basekey_)}},
    // optional bytes ephemeralKey = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.ephemeralkey_)}},
    // optional bytes identityKey = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.identitykey_)}},
    // optional bytes baseKeySignature = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 3, 0,
      PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.basekeysignature_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 id = 1;
    {PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional bytes baseKey = 2;
    {PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.basekey_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bytes ephemeralKey = 3;
    {PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.ephemeralkey_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bytes identityKey = 4;
    {PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.identitykey_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bytes baseKeySignature = 5;
    {PROTOBUF_FIELD_OFFSET(KeyExchangeMessage, _impl_.basekeysignature_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void KeyExchangeMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:textsecure.KeyExchangeMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.basekey_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.ephemeralkey_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.identitykey_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.basekeysignature_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.id_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL KeyExchangeMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const KeyExchangeMessage& this_ = static_cast<const KeyExchangeMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL KeyExchangeMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const KeyExchangeMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:textsecure.KeyExchangeMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_id(), target);
  }

  // optional bytes baseKey = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_basekey();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // optional bytes ephemeralKey = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_ephemeralkey();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  // optional bytes identityKey = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_identitykey();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  // optional bytes baseKeySignature = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    const ::std::string& _s = this_._internal_basekeysignature();
    target = stream->WriteBytesMaybeAliased(5, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:textsecure.KeyExchangeMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t KeyExchangeMessage::ByteSizeLong(const MessageLite& base) {
  const KeyExchangeMessage& this_ = static_cast<const KeyExchangeMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t KeyExchangeMessage::ByteSizeLong() const {
  const KeyExchangeMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:textsecure.KeyExchangeMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // optional bytes baseKey = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_basekey());
    }
    // optional bytes ephemeralKey = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_ephemeralkey());
    }
    // optional bytes identityKey = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_identitykey());
    }
    // optional bytes baseKeySignature = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_basekeysignature());
    }
    // optional uint32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void KeyExchangeMessage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<KeyExchangeMessage*>(&to_msg);
  auto& from = static_cast<const KeyExchangeMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:textsecure.KeyExchangeMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_basekey(from._internal_basekey());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_ephemeralkey(from._internal_ephemeralkey());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_identitykey(from._internal_identitykey());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_internal_set_basekeysignature(from._internal_basekeysignature());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.id_ = from._impl_.id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void KeyExchangeMessage::CopyFrom(const KeyExchangeMessage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:textsecure.KeyExchangeMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void KeyExchangeMessage::InternalSwap(KeyExchangeMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.basekey_, &other->_impl_.basekey_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ephemeralkey_, &other->_impl_.ephemeralkey_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.identitykey_, &other->_impl_.identitykey_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.basekeysignature_, &other->_impl_.basekeysignature_, arena);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata KeyExchangeMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace textsecure
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_WhisperTextProtocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
